### ISSUE TITLE
Add pycodestyle step on Travis

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/autofocus#70]
Add `pycodestyle` to the CI setup for this project to prevent PRs from introducing style issues and to document the preferred style for this project.

See [this example PR](https://github.com/jameslamb/doppel-cli/pull/38/files) for an example of how to add this type of check to your build. Basically you need to run `pycodestyle` command on the repo and can optionally configure what it checks with a `tox.ini` file.

Docs here: http://pycodestyle.pycqa.org/en/latest/intro.html

**Comment by gsganden** [comment]
Right now the code in `predict` wouldn't pass a style check, so it needs to be cleaned up first.
