### ISSUE TITLE
Add test coverage to CI

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/autofocus#71]
Should consider calculating test coverage using `codecov` and a codecov badge in the README.

Doing this basically entails adding this to `.travis.yml`:

```
after_success:
    - codecov
```

And changing the tests to also calculate a test coverage tool, for example

```
script:
    - coverage run setup.py test
    - coverage report -m
```

**Comment by gsganden** [comment]
To my mind test coverage should not be a high priority for this project because it's largely a set of scripts that are used to develop models interactively, rather than e.g. a library of functions with contracts that need to be enforced.
